### ISSUE TITLE
initramfs

### ISSUE THREAD

**Issue by olkur** [lag-linaro/stm32#2]
Hello. 

I am trying to boot Linux on stm32f429-disco and currently get the problem:
.[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.15.0-rc2-00174-g328b4ed-dirty (inisider@kbp1-lhp-f31027) (gcc version 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437] (GNU Tools for ARM Embedded Pro7
[    0.000000] CPU: ARMv7-M [410fc241] revision 1 (ARMv7M), cr=00000000
[    0.000000] CPU: unknown data cache, unknown instruction cache
[    0.000000] OF: fdt: Machine model: STMicroelectronics STM32F429i-DISCO board
[    0.000000] !!! arch/arm/mm/init.c: (0) phys_initrd_size = 0 !!!
[    0.000000] !!! arch/arm/mm/init.c: (1) initrd_start = 0 !!!
[    0.000000] Built 1 zonelists, mobility grouping off.  Total pages: 2032
[    0.000000] Kernel command line: root=/dev/ram0 rootwait
[    0.000000] Dentry cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Inode-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Memory: 7784K/8192K available (1189K kernel code, 127K rwdata, 408K rodata, 63K init, 114K bss, 408K reserved, 0K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0x00000000 - 0x00001000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0x00000000 - 0xffffffff   (4095 MB)
[    0.000000]     lowmem  : 0x90000000 - 0x90800000   (   8 MB)
[    0.000000]       .text : 0x(ptrval) - 0x(ptrval)   (1598 kB)
[    0.000000]       .init : 0x(ptrval) - 0x(ptrval)   (  12 kB)
[    0.000000]       .data : 0x(ptrval) - 0x(ptrval)   ( 128 kB)
[    0.000000]        .bss : 0x(ptrval) - 0x(ptrval)   ( 115 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  Tasks RCU enabled.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] interrupt-controller@40013c00: bank0, External IRQs available:0x7fffff  +-----------------------------+
[    0.000000] clocksource: arm_system_timer: mask: 0xffffff max_cycles: 0xffffff, max_|                             |
[    0.000000] ARM System timer initialized as clocksource                             |  Cannot open /dev/ttyUSB0!  |
[    0.000000] /soc/timer@40000c00: STM32 clockevent driver initialized (32 bits)      |                             |
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474+-----------------------------+
[    0.010000] !!! init/main.c: (1): 0 !!!
[    0.010000] Calibrating delay loop... 110.48 BogoMIPS (lpj=552448)
[    0.100000] pid_max: default: 4096 minimum: 301
[    0.100000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.100000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.100000] Hierarchical SRCU implementation.
[    0.110000] devtmpfs: initialized
[    0.170000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.170000] pinctrl core: initialized pinctrl subsystem
[    0.220000] stm32f429-pinctrl soc:pin-controller: GPIOA bank added
[    0.220000] stm32f429-pinctrl soc:pin-controller: GPIOB bank added
[    0.220000] stm32f429-pinctrl soc:pin-controller: GPIOC bank added
[    0.220000] stm32f429-pinctrl soc:pin-controller: GPIOD bank added
[    0.220000] stm32f429-pinctrl soc:pin-controller: GPIOE bank added
[    0.230000] stm32f429-pinctrl soc:pin-controller: GPIOF bank added
[    0.230000] stm32f429-pinctrl soc:pin-controller: GPIOG bank added
[    0.230000] stm32f429-pinctrl soc:pin-controller: GPIOH bank added
[    0.230000] stm32f429-pinctrl soc:pin-controller: GPIOI bank added
[    0.230000] stm32f429-pinctrl soc:pin-controller: GPIOJ bank added
[    0.240000] stm32f429-pinctrl soc:pin-controller: GPIOK bank added
[    0.240000] stm32f429-pinctrl soc:pin-controller: Pinctrl STM32 initialized
[    0.280000] stm32-dma 40026000.dma-controller: STM32 DMA driver registered
[    0.280000] stm32-dma 40026400.dma-controller: STM32 DMA driver registered
[    0.290000] clocksource: Switched to clocksource arm_system_timer
[    0.350000] I was here!!!
[    0.350000] I was here (2)!!!
[    0.350000] I was here (3) 0 !!!
[    0.350000] I was here (4) 0 !!!
[    0.350000] workingset: timestamp_bits=30 max_order=11 bucket_order=0
[    0.400000] random: fast init done
[    0.440000] io scheduler noop registered (default)
[    0.440000] io scheduler mq-deadline registered
[    0.440000] io scheduler kyber registered
[    0.440000] STM32 USART driver initialized
[    0.440000] 40011000.serial: ttyS0 at MMIO 0x40011000 (irq = 32, base_baud = 5250000) is a stm32-usart
[    0.850000] console [ttyS0] enabled
[    0.860000] stm32_rtc 40002800.rtc: rtc core: registered 40002800.rtc as rtc0
[    0.870000] stm32_rtc 40002800.rtc: Date/Time must be initialized
[    0.880000] i2c /dev entries driver
[    0.890000] input: gpio_keys as /devices/platform/gpio_keys/input/input0
[    0.900000] stm32_rtc 40002800.rtc: setting system clock to 2000-01-01 01:58:20 UTC (946691900)
[    0.920000] Waiting for root device /dev/ram0...

Seems that kernel does not understand where is place of init ramfs.
Maybe need to some additional changes in Linux kernel to run it?

With best regards,
 inisider

**Comment by lag-linaro** [comment]
You need to setup the kernel command line.

I can't remember what is was now, but "root=/dev/ram0 rootwait" is not correct.

**Comment by lag-linaro** [comment]
In fact.  You should probably not be using this repo anymore.

Use Buildroot instead.  Start here:

https://git.busybox.net/buildroot/tree/board/stmicroelectronics/stm32f429-disco/readme.txt

**Comment by olkur** [comment]
Will look for Buildroot.

Thanks.
